Event attendance
Cathella/private-events pull request #1
Opened 2020-07-09 20:19 UTC by Cathella

Rails app using associations between users - (creator and attendee) and events tables. During this project we accomplished numerous tasks that included
- Creating a new user by signing up
- Allowing users to create events when logged in
- Allowing users to attend events
- Show past and upcoming events.

2020-07-10 05:55 UTC, euqueme requested changes
> #### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @Cathella and @misterpaul4 :balloon: :lollipop: 

### Thank you very much for your submission, your project looks amazing and is behaving beautifully :sparkles: your repo, pull request and readme are also very professional :necktie:  there are some changes to make still so let's work on them :construction: :construction_worker_man: :construction_worker_woman: 

#### Behaviour

- [x] The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- your users show page is only showing the events the user is attending to but its also required to show the events the user created also ordered by upcoming and past events

#### Models

##### Event

* [x] it has creation date as attribute ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/event_date_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- validate the presence of your `time` attribute the app shouldn't let your event be created without setting a date

#### Associations

##### User as event creator

* [x] User model: `has_many :events, foreign_key: :creator_id` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- currently you have foreign_key 'event.id' this is not correct it should be :creator_id

##### UsersController

###### `show` action

* [x] lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- Just like I mentioned in the behavior the events created by the user should also appear in the users show page

#### Views & Helpers

* [x] There should be NO application logic in the views nor helpers (no `Post.new`, `Comment.create`, `current_user.friends.find_by(...)`...). Everything connected with data processing should be encapsulated in models and used in controllers.
* [x] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [ ] There should be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- I've put comments straight in the your views where I spotted these rules weren't being followed.

#### Tests

* [ ] models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

- Please add Unit and integration test cases using Rspec and Capybara only

### That's it, team! :raised_hands: 

### Please :pray: do the changes :technologist: :woman_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any question? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-07-10 05:55 UTC, euqueme commented on app/views/attendances/_form.html.erb
> +  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
- [ ] use a helper method to render the if statement in this line there should be no if statements within views or partials

2020-07-10 05:55 UTC, euqueme commented on app/views/events/_form.html.erb
> +    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
- [ ] use a helper method to render the if statement in this line there should be no if statements within views

2020-07-10 05:55 UTC, euqueme commented on app/views/events/_past_event_card.html.erb
> +<% end %>
- [ ] use a helper method to render the if/elseif/else statement in this part of your code there should be no if/elseif/else statements within views if you have several lines you can use a partial to render the markup

2020-07-10 05:55 UTC, euqueme commented on app/views/events/_upcoming_event_card.html.erb
> +<% end %>
- [ ] use a helper method to render the if/elseif/else statement in this part of your code there should be no if/elseif/else statements within views if you have several lines you can use a partial to render the markup

2020-07-10 05:55 UTC, euqueme commented on app/views/events/_upcoming_event_card.html.erb
> +<div class="w-100 bg-secondary text-light py-2 mt-1 font-weight-bold">Created by: <%= User.find(event.creator_id).username %></div>
- [ ] create a helper method that retrieves this `User.find(event.creator_id).username` models shouldn't be called directly in views

2020-07-10 05:55 UTC, euqueme commented on app/views/events/_past_event_card.html.erb
> +<div class="w-100 bg-secondary text-light py-2 mt-1 font-weight-bold">Created by: <%= User.find(event.creator_id).username %></div>
- [ ] create a helper method that retrieves this `User.find(event.creator_id).username` models shouldn't be called directly on the views

2020-07-10 05:55 UTC, euqueme commented on app/views/events/index.html.erb
> +  <% end %>
- [ ] use a helper method to render the if/end statement in this part of your code there should be no if/end statement within views if you have several lines you can use a partial to render the markup

2020-07-10 05:55 UTC, euqueme commented on app/views/home/_event_card.html.erb
> +<% end %>
- [ ]  use a helper method to render the if/elseif/else statement in this part of your code there should be no if/elseif/else statements within views if you have several lines you can use a partial to render the markup

2020-07-10 05:55 UTC, euqueme commented on app/views/home/_event_card.html.erb
> +<div class="w-100 bg-secondary text-light py-2 mt-3 font-weight-bold">Created by: <%= User.find(event.creator_id).username %></div>
- [ ] Use a helper method to get this User.find(event.creator_id).username instead of calling the model directly in the view

2020-07-10 05:55 UTC, euqueme commented on app/views/home/index.html.erb
> +  <% end %>
- [ ] use a helper method to render the if/end statement in this part of your code there should be no if/end statements within views if you have several lines you can use a partial to render the markup

2020-07-10 05:55 UTC, euqueme commented on app/views/layouts/application.html.erb
> +        <% end %>
- [ ] use a helper method to render the if/elseif/else statement in this part of your code there should be no if/elseif/else statements within views if you have several lines you can use a partial to render the markup

2020-07-10 05:55 UTC, euqueme commented on app/views/users/_event_card.html.erb
> +<div class="w-100 bg-secondary text-light py-2 mt-1 font-weight-bold">Created by: <%= User.find(event.creator_id).username %></div>
- [ ] create a helper to put `User.find(event.creator_id).username` the models shouldn't be directly call in views or partials

2020-07-10 05:55 UTC, euqueme commented on app/views/layouts/application.html.erb
> +       <% end %>
- [ ] these if statements should be put in helper methods instead of having them straight in the view

2020-07-10 05:55 UTC, euqueme commented on app/views/users/_event_card.html.erb
> +<% end %>
- [ ] use a helper method to render the if/elseif/else statement in this part of your code there should be no if/elseif/else statements within views if you have several lines you can use a partial to render the markup

2020-07-10 05:55 UTC, euqueme commented on app/views/users/_form.html.erb
> +  <% end %>
- [ ] use a helper method to render the if/end statement in this part of your code there should be no if/end statements within views if you have several lines you can use a partial to render the markup

2020-07-10 05:55 UTC, euqueme commented on app/views/users/_up_event_card.html.erb
> +<div class="w-100 bg-secondary text-light py-2 mt-1 font-weight-bold">Created by: <%= User.find(event.creator_id).username %></div>
- [ ] Put the `User.find(event.creator_id).username` in a helper the models shouldn't be directly called in views

2020-07-10 05:55 UTC, euqueme commented on app/views/users/_up_event_card.html.erb
> +<% end %>
- [ ] use a helper method to render the if/elseif/else statement in this part of your code there should be no if/elseif/else statements within views if you have several lines you can use a partial to render the markup

2020-07-10 05:55 UTC, euqueme commented on lib/templates/erb/scaffold/_form.html.erb
> +  <%%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
- [ ] This if statement should be put in a helper method instead of having it straight in the view

2020-07-14 22:07 UTC, wathigo requested changes
### Changes Required.
Great work so far :clap: 
Let's fix a few issues with the tests.

**REQUIRED**
* Let's separate model tests and feature tests(integration tests)
Currently, user model unit test and integration tests for authentication feature are all in the same file.

* Lets also separate model and integration tests inside `spec/model/event_spec.rb`. We can create a separate folder for each one of these.
Let's use different folders for unit and integration tests. 
I recommend using [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers) only for model unit tests which tests for validations and associations.

**After working on the changes, submit another request for review.**

**Good luck :computer: 
Simon Wathigo.**

2020-07-17 06:01 UTC, Ispirett approved these changes
## Status Approved :100: 
Great job folks, you did great will all the changes made. :+1:

2020-07-17 06:18 UTC, merged